<div class="container-fluid"><h4 class="page-title">
        </h4> <div class="row"><div class="col-md-12"><div class="card">
                <div class="card-body table-responsive">
                    <div id="data_table_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                        <div class="row"><div class="col-sm-12 col-md-6">
                                <div class="dataTables_length" id="data_table_length"><label>Show
                                        <select name="data_table_length" aria-controls="data_table" class="custom-select custom-select-sm form-control form-control-sm">
                                            <option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div></div><div class="col-sm-12 col-md-6"><div id="data_table_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="data_table"></label></div></div></div><div class="row"><div class="col-sm-12"><table id="data_table" class="table table-bordered table-striped table-hover dataTable w-100 no-footer" role="grid" aria-describedby="data_table_info" style="width: 1012px;"><thead><tr role="row"><th class="sorting_desc" tabindex="0" aria-controls="data_table" rowspan="1" colspan="1" style="width: 64px;" aria-sort="descending" aria-label="Sl. No: activate to sort column ascending">Sl. No</th><th class="sorting" tabindex="0" aria-controls="data_table" rowspan="1" colspan="1" style="width: 174px;" aria-label="Name: activate to sort column ascending">Name</th><th class="sorting" tabindex="0" aria-controls="data_table" rowspan="1" colspan="1" style="width: 247px;" aria-label="Email: activate to sort column ascending">Email</th><th class="sorting" tabindex="0" aria-controls="data_table" rowspan="1" colspan="1" style="width: 120px;" aria-label="Department: activate to sort column ascending">Department</th><th class="sorting" tabindex="0" aria-controls="data_table" rowspan="1" colspan="1" style="width: 50px;" aria-label="Role: activate to sort column ascending">Role</th><th class="sorting" tabindex="0" aria-controls="data_table" rowspan="1" colspan="1" style="width: 83px;" aria-label="Status: activate to sort column ascending">Status</th><th class="sorting_disabled" rowspan="1" colspan="1" style="width: 100px;" aria-label="Action">Action</th></tr></thead><tbody><tr role="row" class="odd"><td class="sorting_1">4</td><td>Deb Nandan Dutta</td><td>admin@ready.com</td><td>IT</td><td>Test</td><td><span class="badge badge-success">Active</span></td><td><a href="http://localhost/crm/staff-edit/4" class="badge bg-primary text-white" title="Edit">
                                                <i class="fa fa-pencil"></i>
                                            </a><form action="http://localhost/crm/staff-status/4" method="POST">
                                                <input type="hidden" name="_token" value="bAea8Kh7gaCqGKmltKgXfHFAIXtJy4NjmuWiS5RV">
                                                <input type="hidden" name="status" value="0">
                                                <button type="submit" class="badge bg-red pointer">Inactive</button>
                                            </form></td></tr></tbody></table><div id="data_table_processing" class="dataTables_processing card" style="display: none;">Processing...</div></div></div><div class="row"><div class="col-sm-12 col-md-5"><div class="dataTables_info" id="data_table_info" role="status" aria-live="polite">Showing 1 to 1 of 1 entries</div></div><div class="col-sm-12 col-md-7"><div class="dataTables_paginate paging_simple_numbers" id="data_table_paginate"><ul class="pagination"><li class="paginate_button page-item previous disabled" id="data_table_previous"><a href="#" aria-controls="data_table" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li><li class="paginate_button page-item active"><a href="#" aria-controls="data_table" data-dt-idx="1" tabindex="0" class="page-link">1</a></li><li class="paginate_button page-item next disabled" id="data_table_next"><a href="#" aria-controls="data_table" data-dt-idx="2" tabindex="0" class="page-link">Next</a></li></ul></div></div></div></div></div></div></div></div></div>